Repository betagouv/aides-jeunes, pull requests merged in 2022-02, with the labels that each got.

#2395 [562] Ajouter des fonctions de linting de certains champs de l'outil de contribution
  contribuer/public/admin/description.js
  contribuer/public/admin/formatter.js
  contribuer/public/admin/index.html
Labels: development

#2405 fix: laisse les champs vides à undefined
  contribuer/public/admin/description.js
  contribuer/public/admin/formatter.js
Labels: development, bugfix

#2375 Met à jour le contenu éditorial des aides
  data/benefits/additional-attributes/fonds-solidarite-logement.js
  data/benefits/additional-attributes/fsl-eligibilite.js
  data/benefits/javascript/centre-val-de-loire-ordinateur.yml
  data/benefits/javascript/centre-val-de-loire-pass-yeps.yml
  data/benefits/openfisca/alfortville_noel_enfants.yml
  data/benefits/openfisca/bourse_criteres_sociaux.yml
  data/benefits/openfisca/eure_et_loir_eligibilite_adefip.yml
  data/benefits/openfisca/iwuy_aide_mobilite_permis.yml
  data/benefits/openfisca/msa_portes_de_bretagne_aide_permis.yml
  data/benefits/openfisca/ppa.yml
Labels: development

#2407 Fixe la version de vue/cli pour éviter les bugs lors de l'installation d'un package
  package-lock.json
  package.json
Labels: development

#2408 Met à jour les versions d'openfica
  backend/lib/definitions.js
  data/benefits/openfisca/agepi.yml
  openfisca/requirements.txt
Labels: development, ⚡ fast review

#2412 [568] remplace le dossier State par state
  src/lib/state/blocks.js
  src/lib/state/generator.js
  src/lib/state/index.js
  src/lib/state/steps.js
  src/plugins/state-service.js
  src/store.js
  src/views/simulation/mutualized-step.vue
  src/views/simulation/recapitulatif.vue
Labels: development, ⚡ fast review

#2398 [489] Intégration de github actions
  .circleci/config.yml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  README.md
  package.json
Labels: development

#2415 Supprime les .native après @click : plus utilisé dans v3
  src/components/action-buttons.vue
  src/components/summary.vue
  src/components/titre-chapitre.vue
  src/views/simulation/recapitulatif.vue
Labels: development, ⚡ fast review

#2414 Supprime isOldSituation
  src/components/summary.vue
  src/views/simulation/resultats.vue
Labels: development, ⚡ fast review

#2409 Ajoute un event matomo `Montant inattendu`
  src/components/droit-estime.vue
Labels: development, ⚡ fast review

#2413 Ajoute les aides et institutions de la version 2.0.13 d'aides velo
  data/institutions/cc_flandre_interieure.yml
  data/institutions/cc_rives_de_moselle.yml
  data/institutions/ville_divonne_les_bains.yml
  data/institutions/ville_merignac.yml
  package-lock.json
  package.json
  public/img/logo_cc_flandre_interieure.jpg
  public/img/logo_cc_rives_de_moselle.png
  public/img/logo_ville_divonne_les_bains.png
  public/img/logo_ville_merignac.png
Labels: development, ⚡ fast review

#2410 Corrige de debug parcours
  src/components/progress.vue
Labels: development, ⚡ fast review

#2376 Crée une page dédiée pour chaque aide
  src/components/benefit-cta.vue
  src/components/droit-estime.vue
  src/router.js
  src/views/aide.vue
  src/views/liste-aides.vue
Labels: development

#2431 Ajout de fonctionnalités à la CI
  .github/workflows/ci.yml
Labels: development, ⚡ fast review

#2430 [496] Créer un bot Mattermost qui poste les réponses au sondage à chaque réponse
  backend/config/index.js
  backend/controllers/followups.js
  backend/lib/mattermost-bot/mattermost.js
  backend/lib/mattermost-bot/poll-result.js
  mock.js
Labels: development

#2411 [574] Éviter le crash de l'app en npm run front quand on essaie de récupérer le payload openfisca d'une simulation qui n'existe pas
  mock.js
Labels: development, bugfix, ⚡ fast review

#2443 Corrige le bug pour pouvoir utiliser npm ci à nouveau
  package-lock.json
Labels: development, bugfix

#2437 Ajoute une authentification à github
  backend/config/index.js
  backend/controllers/github.js
  backend/routes/github.js
Labels: development

#2447 Simplifie la réutilisation de la barre de progression
  src/components/progress-bar.vue
  src/views/simulation.vue
Labels: development, ⚡ fast review

#2449 Remplace le i de en savoir plus par un svg
  src/components/en-savoir-plus.vue
  src/styles/partials/desktop/_ui-kit.scss
Labels: development, ⚡ fast review

#2444 [528][588] Mettre une limite dans la date de naissance / Aligner les montants à droite
  src/components/input-date.vue
  src/components/input-number.vue
  src/lib/famille-properties.js
  src/lib/individu-properties.js
  src/lib/parents-properties.js
  src/views/simulation/mutualized-step.vue
Labels: development, ⚡ fast review

#2450 [585] Permettre à une personne de l'équipe d'accéder à un résultat de sondage intégral et à la simulation associée
  backend/config/index.js
  backend/controllers/followups.js
  backend/controllers/github.js
  backend/lib/mattermost-bot/poll-result.js
  backend/routes/followups.js
  backend/routes/github.js
  mock.js
  src/router.js
  src/views/accompagnement/liste.vue
Labels: development

#2452 Met à jour les aides velo
  data/institutions/ca_lannion_tregor_communaute.yml
  data/institutions/ca_pays_de_saint_malo_agglomeration.yml
  data/institutions/cc_dieulefit_bourdeaux.yml
  data/institutions/cc_genevois.yml
  data/institutions/cu_du_grand_reims.yml
  data/institutions/ville_granville.yml
  data/institutions/ville_lievin.yml
  data/institutions/ville_perros_guirec.yml
  package-lock.json
  package.json
  public/img/logo_ca_lannion_tregor_communaute.png
  public/img/logo_ca_pays_de_saint_malo_agglomeration.png
  public/img/logo_cc_dieulefit_bourdeaux.jpg
  public/img/logo_cc_genevois.jpg
  public/img/logo_cu_du_grand_reims.png
  public/img/logo_ville_granville.png
  public/img/logo_ville_lievin.png
  public/img/logo_ville_perros_guirec.png
Labels: development, ⚡ fast review

#2434 fix: corrige les problèmes d'iframe sur webkit
  backend/controllers/answers.js
Labels: bugfix

#2455 [590] incrémenter la version des stats x/n
  backend/config/index.js
  src/mixins/statistics.js
  vue.config.js
Labels: development

#2456 Sécurise les cookies en fonction de l'environnement
  backend/controllers/answers.js
Labels: development, bugfix, ⚡ fast review

#2454 Corrige les bugs d'affichage sur les questions optionnelles
  lib/answers.js
  src/views/simulation/Ressources/enfants.vue
  src/views/simulation/mutualized-step.vue
Labels: development, ⚡ fast review

#2457 Définit la couleur de l'icone via la couleur primaire
  src/styles/partials/desktop/_buttons.scss
Labels: development, ⚡ fast review

#2392 Utilise des variables pour le contexte et l'email de contact
  public/index.html
  src/directives/mail.js
  src/mixins/contact-email.js
  src/store.js
  src/views/accessibilite.vue
  src/views/confidentialite.vue
  src/views/contact.vue
  src/views/redirection.vue
  src/views/simulation/resultats/attendu.vue
  vue.config.js
Labels: development

#2458 Met à jour openfisca
  openfisca/requirements.txt
Labels: development, ⚡ fast review

#2460 Met à jour les aides velo
  data/institutions/cc_grand_saint_emilionnais.yml
  data/institutions/ville_queven.yml
  package-lock.json
  package.json
  public/img/logo_cc_grand_saint_emilionnais.jpg
  public/img/logo_ville_queven.png
Labels: development, ⚡ fast review

#2416 Permet de récupérer les étapes avec node
  lib/chapters.js
  lib/state/blocks.js
  lib/state/generator.js
  lib/state/index.js
  lib/state/steps.js
  src/components/titre-chapitre.vue
  src/lib/mutualized-steps.js
  src/plugins/state-service.js
  src/store.js
  src/views/simulation/mutualized-step.vue
  src/views/simulation/recapitulatif.vue
  tools/get-all-steps.js
Labels: development, ⚡ fast review

#2453 Correctifs pour l'outil d'accompagnement
  backend/controllers/followups.js
  backend/lib/mattermost-bot/poll-result.js
  backend/models/followup.js
  backend/routes/followups.js
  src/router.js
  src/views/accompagnement/liste.vue
Labels: development

#2484 [612] Corrige la page d'affichage des résultats indiquée dans les emails
  backend/controllers/followups.js
Labels: development, bugfix, ⚡ fast review

#2486 Correctifs
  backend/controllers/answers.js
  backend/controllers/followups.js
  lib/situations.js
Labels: development, bugfix

#2489 Supprime l'affichage d'erreur sans avoir appuyé sur le bouton pour éviter le doublon
  src/components/error-block.vue
Labels: development, ⚡ fast review

#2488 Offboarding
  backend/config/index.js
Labels: development
