Repository betagouv/aides-jeunes, pull requests merged in 2022-01, with the labels that each got.

#2269 Supprime la page Foyer.vue
  src/views/Foyer.vue
Labels: development

#2266 [464] Utiliser une image Docker en CI avec Node v16
  .circleci/config.yml
Labels: development

#2273 [473] Corrige un bug lors de l'accès à la page de suivi
  src/views/Suivi.vue
Labels: development, bugfix

#2265 [415] Prend en compte les retours d'utilisation de Netlify CMS
  contribuer/public/admin/config.yml
Labels: development

#2272 Met à jour la version de node
  lib/Benefits/compute-javascript.js
  netlify.toml
  package-lock.json
  package.json
  src/components/InputDate.vue
Labels: development

#2056 Ajoute Célibataire dans `_situation` des parents
  backend/lib/definitions.js
  src/lib/IndividuProperties.js
  src/lib/ParentsProperties.js
  src/plugins/ABTestingService.js
  src/router.js
Labels: development

#2277 Met à jour le Header et le Footer 1j1s
  src/components/Footer1J1S.vue
  src/components/Header1J1S.vue
Labels: development

#2278 [467] Réparer la récupération des paramètres OpenFisca en mode npm run front
  backend/lib/openfisca/parameters.js
  mock.js
Labels: development, bugfix

#2287 [468][477][483] Modularisation du champ DepCom et correction d'un bug de corruption
  src/components/InputDepcom.vue
  src/mixins/DepcomMixin.js
  src/views/Simulation/Individu/_BourseCriteresSociauxCommuneDomicileFamilial.vue
  src/views/Simulation/Menage/Depcom.vue
Labels: development, bugfix

#1940 Simplifie le code avec le chaining operator
  backend/controllers/answers.js
  backend/controllers/outils.js
  backend/lib/mes-aides/distance.js
  backend/lib/migrations/to-v2.js
  backend/lib/openfisca/mapping/index.js
  backend/lib/openfisca/parameters.js
  backend/models/answer.js
  data/benefits/custom/index.js
  data/index.js
  lib/benefits/compute.js
  lib/benefits/customization.js
  lib/resources.js
  lib/ressource.js
  lib/situations.js
  mock.js
  src/components/action-buttons.vue
  src/components/benefit-cta-link.vue
  src/components/droits-details.vue
  src/components/en-savoir-plus-content.vue
  src/components/en-savoir-plus.vue
  src/components/etablissement.vue
  src/components/input-date.vue
  src/components/modal.vue
  src/components/offline-results.vue
  src/components/ressource/types.vue
  src/components/summary.vue
  src/components/titre-chapitre.vue
  src/lib/State/blocks.js
  src/lib/State/index.js
  src/lib/chapters.js
  src/lib/commune.js
  src/lib/hint.js
  src/lib/menage-properties.js
  src/lib/situation.js
  src/lib/utils.js
  src/lib/warnings.js
  src/mixins/feedback-utils.js
  src/mixins/resultats.js
  src/mixins/statistics.js
  src/plugins/state-service.js
  src/router.js
  src/views/lieux.vue
  src/views/lieux/details.vue
  src/views/simulation.vue
  src/views/simulation/Ressources/fiscales.vue
  src/views/simulation/mutualized-step.vue
  src/views/simulation/recapitulatif.vue
  src/views/simulation/resultat-inattendu.vue
  src/views/simulation/resultats-detail.vue
  src/views/simulation/resultats.vue
  src/views/simulation/resultats/attendu.vue
  src/views/simulation/resultats/lieux-generiques.vue
  src/views/simulation/resultats/lieux.vue
  vue.config.js
Labels: development

#2276 Ajoute le quotient_familial dans l'outil de contribution
  backend/lib/openfisca/mapping/index.js
  backend/lib/openfisca/test.js
  contribuer/public/admin/config.yml
  data/benefits/javascript/bourgogne-franche-comte-dynastage.yml
  data/benefits/javascript/bretagne-jeune-international.yml
  data/benefits/javascript/caf-allier-aide-bafa-session-generale.yml
  data/benefits/javascript/caf-aube-aide-bafa-approfondissement.yml
  data/benefits/javascript/caf-aube-aide-bafa-generale.yml
  data/benefits/javascript/caf-bouches-du-rhone-aide-bafa-approfondissement.yml
  data/benefits/javascript/caf-bouches-du-rhone-aide-bafa-generale.yml
  data/benefits/javascript/caf-calvados-aide-bafa-approfondissement.yml
  data/benefits/javascript/caf-calvados-aide-bafa-générale.yml
  data/benefits/javascript/caf-charente-aide-bafa-generale.yml
  data/benefits/javascript/caf-charente-maritime-aide-bafa-approfondissement.yml
  data/benefits/javascript/caf-charente-maritime-aide-bafa-generale.yml
  data/benefits/javascript/caf-correze-aide-bafa-generale.yml
  data/benefits/javascript/caf-cotes-armor-aide-bafa-approfondissement.yml
  data/benefits/javascript/caf-creuse-aide-bafa-generale.yml
  data/benefits/javascript/caf-drome-aide-bafa-session-generale.yml
  data/benefits/javascript/caf-eure-aide-bafa-generale.yml
  data/benefits/javascript/caf-haute-vienne-aide-bafa-generale.yml
  data/benefits/javascript/caf-hautes-pyrenees-aide-bafa-generale.yml
  data/benefits/javascript/caf-indre-et-loire-aide-bafa-approfondissement.yml
  data/benefits/javascript/caf-indre-et-loire-aide-bafa-generale.yml
  data/benefits/javascript/caf-loir-et-cher-aide-bafa-approfondissement.yml
  data/benefits/javascript/caf-loir-et-cher-aide-bafa-generale.yml
  data/benefits/javascript/caf-lot-et-garonne-aide-bafa-approfondissement.yml
  data/benefits/javascript/caf-lot-et-garonne-aide-bafa-generale.yml
  data/benefits/javascript/caf-meurthe-et-moselle-aide-bafa-approfondissement.yml
  data/benefits/javascript/caf-meurthe-et-moselle-aide-bafa-generale.yml
  data/benefits/javascript/caf-sarthe-aide-bafa-approfondissement.yml
  data/benefits/javascript/caf-sarthe-aide-bafa-generale.yml
  data/benefits/javascript/caf-seine-maritime-aide-bafa-approfondissement.yml
  data/benefits/javascript/caf-tarn-et-garonne-aide-bafa-approfondissement.yml
  data/benefits/javascript/caf-tarn-et-garonne-aide-bafa-generale.yml
  data/benefits/javascript/caf-var-aide-bafa-approfondissement.yml
  data/benefits/javascript/caf-vaucluse-aide-bafa-approfondissement.yml
  data/benefits/javascript/caf-vaucluse-aide-bafa-generale.yml
  data/benefits/javascript/caf-vienne-aide-bafa-generale.yml
  data/benefits/javascript/caf-vosges-aide-bafa-generale.yml
  data/benefits/javascript/caf_pas_de_calais-aide-au-bafa-pour-une-session-de-formation-générale.yml
  data/benefits/javascript/normandie-pass-monde-etudes-superieures.yml
  lib/benefits/compute-javascript.js
Labels: development

#2291 Retirer le lien sos
  src/views/simulation/resultats.vue
Labels: development

#2305 Simplifie la gestion de l'event du component InputNumber
  src/components/input-number.vue
  src/components/ressource/auto-entreprise.vue
  src/components/ressource/exploitant-agricole.vue
  src/components/ressource/micro-entreprise.vue
  src/components/ressource/montants.vue
  src/components/ressource/profession-liberale.vue
Labels: development

#2303 Corrige la directive analytics
  src/directives/analytics.js
  src/directives/mail.js
  src/directives/select-on-click.js
Labels: development

#2271 Déplace le contenu des aides customs vers les fichiers yml
  data/benefits/additional-attributes/apa-eligibilite.js
  data/benefits/additional-attributes/fonds-solidarite-logement.js
  data/benefits/additional-attributes/fsl-eligibilite.js
  data/benefits/additional-attributes/index.js
  data/benefits/additional-attributes/occitanie-carte-transport-scolaire-lio.js
  data/benefits/custom/index.js
  data/benefits/openfisca/aide_logement.yml
  data/benefits/openfisca/apa_eligibilite.yml
  data/benefits/openfisca/css_participation_forfaitaire.yml
  data/benefits/openfisca/fsl_eligibilite.yml
  data/benefits/openfisca/garantie_jeunes.yml
  data/benefits/openfisca/livret_epargne_populaire_taux.yml
  data/benefits/openfisca/occitanie_carte_transport_scolaire_lio.yml
  data/benefits/openfisca/ppa.yml
  data/benefits/openfisca/rsa.yml
  data/index.js
  tests/unit/benefits-generate.spec.js
Labels: development

#2308 [510] Supprime les fichiers et packages inutiles présents dans le repository
  .eslintignore
  .eslintrc.js
  .modernizrrc
  .prettierrc.json
  LICENSE.AGPL.txt
  LICENSE.md
  Procfile
  babel.config.js
  configure.js
  cypress.json
  import-tests.sh
  package-lock.json
  package.json
Labels: development

#2310 fix: corrige la génértion de sitemap.xml
  public/map.xml
  vue.config.js
Labels: development, bugfix

#2279 Met à jour openfisca
  backend/lib/openfisca/mapping/individu/ressources.js
  backend/lib/openfisca/parameters.js
  data/benefits/additional-attributes/index.js
  data/benefits/openfisca/cheque_energie.yml
  lib/benefits/compute.js
  openfisca/requirements.txt
  src/lib/State/blocks.js
  src/lib/individu-properties.js
Labels: development

#2322 [511] Ajouter le niveau d'accessibilité dans le footer
  src/components/footer-1j1s.vue
Labels: development, bugfix

#2323 [469] Vérifier si scrollBehavior correspond à du code mort
  package-lock.json
  package.json
  src/main.js
  src/plugins/scroll-service.js
Labels: development

#2324 optimization: réduction lossless d'images
  src/assets/images/arrow-back.png
  src/assets/images/home_illustration.png
Labels: optimization

#2312 Simplifie le header de la page d'aide et corrige le bug en moyenne écran
  contribuer/public/css/style.css
  src/components/droit-estime.vue
  src/components/droit-header.vue
  src/components/droits-details.vue
  src/styles/partials/desktop/_resultats.scss
  src/styles/partials/mobile/_resultats.scss
  src/styles/partials/tablet/_resultats.scss
  src/views/suivi.vue
Labels: development

#2319 N'affiche pas de légende pour les aides de type bool
  src/components/droit-estime.vue
Labels: development

#2330 Corrige le `quotient_familial` dans l'outil de contribution
  contribuer/public/admin/config.yml
Labels: development

#2343 Utilise les packages openfisca au lieu de leur référence git
  openfisca/requirements.txt
Labels: development

#2333 [448] Ajouter une question à choix multiple pour les aides au financement de vélo
  cypress/integration/base.spec.js
  cypress/integration/family.spec.js
  cypress/integration/handicap.spec.js
  cypress/integration/student.spec.js
  cypress/utils/form.js
  cypress/utils/projet.js
  lib/benefits/compute-aides-velo.js
  lib/benefits/compute.js
  src/components/multiple-answers.vue
  src/lib/State/blocks.js
  src/lib/individu-properties.js
  src/lib/utils.js
  src/views/simulation/mutualized-step.vue
  tests/unit/compute-aides-velo-benefits.spec.js
Labels: development

#2347 [530] Ajoute un champ participation aux aides
  contribuer/public/admin/config.yml
  contribuer/public/admin/main.js
  src/components/droits-details.vue
  src/mixins/droit-mixin.js
Labels: development

#2345 Simplifie le récapitulatif et améliore l'affichage des revenus
  src/lib/recapitulatif.js
  src/store.js
  src/styles/partials/desktop/_recapitulatif.scss
  src/views/simulation/recapitulatif.vue
Labels: development

#2304 Ajoute une validation des données du modèle `answers` en db
  backend/lib/definitions.js
  backend/models/answer.js
Labels: development

#2354 Améliorations de l'outil de contribution liées au coût
  contribuer/public/admin/config.yml
  contribuer/public/admin/main.js
  src/components/droits-details.vue
  src/mixins/droit-mixin.js
Labels: development

#2311 [500] Mettre à jour les différents package présentant des CVE
  package-lock.json
Labels: dependencies, development

#2344 Désactive le bouton suivant lorsque qu'une réponse est requise mais qu'elle n'est pas renseignée
  src/components/action-buttons.vue
  src/mixins/depcom-mixin.js
  src/mixins/individu-mixin.js
  src/styles/partials/desktop/_buttons.scss
  src/views/simulation/Menage/depcom.vue
  src/views/simulation/individu/_bourse-criteres-sociaux-commune-domicile-familial.vue
  src/views/simulation/individu/_first-name.vue
  src/views/simulation/logement.vue
  src/views/simulation/mutualized-step.vue
Labels: development

#2381 Corrige le bug des ressources
  src/views/simulation/Ressources/montants.vue
Labels: development

#2377 Met à jour les dépendances
  contribuer/package-lock.json
  package-lock.json
Labels: development

#2378 Corrige les erreurs d'interpolation dans les emails text
  backend/lib/mes-aides/emails/initial.js
Labels: development
