Repository betagouv/aides-jeunes, pull requests merged in 2022-03, with the labels that each got.

#2494 Ajout d'un utilisateur github
  backend/config/index.js
Labels: development

#2479 Créer un script node pour évaluer les aides d'une simulation dans la BDD
  README.md
  package.json
  tools/evaluate-benefits.js
Labels: development, ⚡ fast review

#2495 Supprime une ligne de test dans les tests e2e
  cypress/utils/results.js
Labels: development, ⚡ fast review

#2498 Corrige le bouton recapitulatif en mode tablette
  src/styles/partials/desktop/_ui-kit.scss
  src/styles/partials/mobile/_ui-kit.scss
  src/styles/partials/tablet/_ui-kit.scss
Labels: development, ⚡ fast review

#2475 Prépare l'ajout de Matomo à l'outil de contribution
  contribuer/public/admin/index.html
Labels: development, ⚡ fast review

#2492 Utilise le component Warning
  src/components/action-buttons.vue
  src/components/droits-details.vue
  src/components/droits-list.vue
  src/components/error-block.vue
  src/components/offline-results.vue
  src/components/warning-message.vue
  src/styles/partials/desktop/_resultats.scss
  src/views/simulation.vue
  src/views/simulation/Menage/depcom.vue
  src/views/simulation/individu/_bourse-criteres-sociaux-commune-domicile-familial.vue
  src/views/simulation/resultats.vue
  src/views/simulation/resultats/attendu.vue
Labels: development

#2487 Simplifie pour accélérer le chargement des infos de communes
  backend/controllers/outils.js
Labels: development

#2463 Améliore la gestion d'affichage en iframe
  backend/config/front-only.js
  backend/config/index.js
  package.json
  src/components/iframe-layout.vue
  src/context/index.js
  src/views/iframe.vue
  src/views/stats.vue
  vue.config.js
Labels: development

#2511 Corrige le champ situationId dans le sujet des emails
  src/components/feedback.vue
Labels: development, ⚡ fast review

#2491 Amélioration rgaa
  src/components/summary.vue
  src/styles/partials/desktop/_buttons.scss
Labels: development

#2513 Supprime l'icone pour aides bool
  cypress/utils/results.js
  lib/benefits/details.js
  src/components/droit-estime.vue
  src/styles/partials/desktop/_ui-kit.scss
Labels: development, ⚡ fast review

#2499 Corrige la connexion à l'outil d'accompagnement
  src/views/accompagnement/liste.vue
Labels: development, bugfix, ⚡ fast review

#2525 Ajoute un console log pour détecter les erreurs de redirection
  backend/controllers/github.js
  src/views/accompagnement/liste.vue
Labels: development

#2522 Change l'ordre du bouton modifier sur la page Récapitulatif
  src/styles/partials/tablet/_recapitulatif.scss
Labels: development, ⚡ fast review

#2493 [621] Vérifier NODE_ENV en CI
  .github/workflows/ci.yml
  package.json
Labels: development, bugfix

#2530 [440] Ajouter un lien sur la home des preview app lors de l'ajout ou modification d'une aide dans netlify
  src/components/bandeau-demo.vue
  vue.config.js
Labels: development, ⚡ fast review

#2531 Fix/accompagnement map
  backend/controllers/github.js
  src/views/accompagnement/liste.vue
Labels: development, bugfix

#2532 update: optimisation et logging
  backend/controllers/github.js
  src/views/accompagnement/liste.vue
Labels: development, bugfix

#2514 Repasse aux id de droits dans le suivi via matomo
  src/views/simulation/resultats-detail.vue
  src/views/simulation/resultats.vue
Labels: development, ⚡ fast review

#2560 [651] Les units tests échouent lorsqu'une image est spécifiée pour une aide
  tests/unit/benefits-description.spec.js
Labels: development, bugfix, ⚡ fast review

#2469 Ne demande pas la variable `fsl_eligibilite` pour le département du 28
  backend/lib/openfisca/mapping/index.js
Labels: development, ⚡ fast review

#2581 [657] Certaines régions sont manquantes dans l'outil de contribution
  contribuer/public/admin/config.yml
Labels: development, bugfix, ⚡ fast review

#2591 Ajoute le bouton Accéder aux résultats dans le récapitulatif lorsque la simulation est terminée
  src/components/progress-bar.vue
  src/mixins/progress-mixin.js
  src/views/simulation/recapitulatif.vue
Labels: development, ⚡ fast review

#2346 Remplace answers par simulation
  backend/controllers/followups.js
  backend/controllers/simulation.js
  backend/controllers/teleservices/index.js
  backend/lib/definitions.js
  backend/lib/mes-aides/emails/initial.js
  backend/lib/mes-aides/emails/survey.js
  backend/lib/migrations/apply.js
  backend/lib/migrations/index.js
  backend/lib/migrations/looper.sh
  backend/lib/migrations/to-v4.js
  backend/lib/migrations/to-v5.js
  backend/lib/migrations/to-v6.js
  backend/lib/migrations/to-v7.js
  backend/lib/migrations/to-v8.js
  backend/lib/mongo-connector.js
  backend/lib/openfisca/mapping/index.js
  backend/lib/teleservices/openfisca-axe.js
  backend/models/followup.js
  backend/models/simulation.js
  backend/routes/simulation.js
  cypress/utils/navigate.js
  lib/situations.js
  mock.js
  public/robots.txt
  src/components/offline-results.vue
  src/components/ressource/types.vue
  src/lib/recapitulatif.js
  src/mixins/individu-mixin.js
  src/mixins/progress-mixin.js
  src/mixins/resultats.js
  src/store.js
  src/views/simulation/Menage/depcom.vue
  src/views/simulation/Menage/loyer.vue
  src/views/simulation/Ressources/montants.vue
  src/views/simulation/enfants.vue
  src/views/simulation/logement.vue
  src/views/simulation/mutualized-step.vue
  src/views/simulation/recapitulatif.vue
  src/views/simulation/resultats/attendu.vue
  tests/unit/situation.spec.js
  tools/evaluate-benefits.js
  tools/mjml.js
Labels: development

#2524 [629] Ajouter un lien vers l'outil de contribution sur chaque page dédiée d'aide /aides/:slug
  backend/config/index.js
  src/components/droits-contributions.vue
  src/components/droits-details.vue
  src/views/aide.vue
  src/views/simulation/resultats-detail.vue
  vue.config.js
Labels: development, ⚡ fast review

#2594 Corrige le calcul du nombre d'aide total
  vue.config.js
Labels: development, bugfix, ⚡ fast review

#2523 Ajoute la réponse "pas concerné" pour la question `enceinte`
  backend/lib/definitions.js
  backend/lib/migrations/to-v9.js
  backend/lib/openfisca/mapping/individu/index.js
  cypress/utils/profil.js
  src/lib/individu-properties.js
  src/store.js
Labels: development

#2582 [656] Lors de la création d'une institution, le code insee est optionnel dans l'interface mais obligatoire dans les tests
  contribuer/public/admin/config.yml
Labels: development, bugfix, ⚡ fast review

#2621 Corrige le chemin des logos d'aides dans l'outil de contribution
  contribuer/public/admin/config.yml
Labels: development, bugfix, ⚡ fast review

#2579 Met à jour le package aides vélo
  data/institutions/ca_de_la_porte_du_hainaut.yml
  data/institutions/ca_de_saintes.yml
  data/institutions/ca_grand_lac.yml
  data/institutions/ca_le_grand_perigueux.yml
  data/institutions/ca_quimperle_communaute.yml
  data/institutions/ca_tulle_agglo.yml
  data/institutions/ca_vienne_condrieu.yml
  data/institutions/ca_villefranche_beaujolais_saone.yml
  data/institutions/cc_des_portes_de_rosheim.yml
  data/institutions/cc_du_pays_rhenan.yml
  data/institutions/cc_loire_layon_aubance.yml
  data/institutions/cc_yvetot_normandie.yml
  data/institutions/departement_saone_et_loire.yml
  data/institutions/ville_camon.yml
  data/institutions/ville_chalette_sur_loing.yml
  data/institutions/ville_correze.yml
  data/institutions/ville_dardilly.yml
  data/institutions/ville_epernay.yml
  data/institutions/ville_la_motte_servolex.yml
  data/institutions/ville_le_bourget_du_lac.yml
  data/institutions/ville_quesnoy_sur_deule.yml
  package-lock.json
  package.json
  public/img/logo_ca_de_la_porte_du_hainaut.png
  public/img/logo_ca_de_saintes.png
  public/img/logo_ca_grand_lac.png
  public/img/logo_ca_le_grand_perigueux.png
  public/img/logo_ca_quimperle_communaute.png
  public/img/logo_ca_tulle_agglo.png
  public/img/logo_ca_vienne_condrieu.png
  public/img/logo_ca_villefranche_beaujolais_saone.png
  public/img/logo_cc_des_portes_de_rosheim.jpg
  public/img/logo_cc_du_pays_rhenan.png
  public/img/logo_cc_loire_layon_aubance.png
  public/img/logo_cc_yvetot_normandie.png
  public/img/logo_ville_camon.jpg
  public/img/logo_ville_chalette_sur_loing.png
  public/img/logo_ville_correze.png
  public/img/logo_ville_dardilly.png
  public/img/logo_ville_epernay.png
  public/img/logo_ville_la_motte_servolex.png
  public/img/logo_ville_le_bourget_du_lac.png
  public/img/logo_ville_quesnoy_sur_deule.png
  tests/unit/aides-velo-benefit-generator.spec.js
  tools/generate-missing-institutions-aides-velo.js
Labels: development

#2644 Corrige le code Insee pour le département de la Vendée
  data/institutions/departement_vendee.yml
Labels: ⚡ fast review

#2646 Renomme les logos des institutions Guadeloupe et Martinique
  data/institutions/guadeloupe.yml
  data/institutions/martinique.yml
  public/img/logo_guadeloupe.png
  public/img/logo_martinique.png
Labels: ⚡ fast review
