Repository betagouv/aides-jeunes, pull requests merged in 2022-05, with the labels that each got.

#2820 Ajoute un ``i`` ``en savoir plus`` à la question sur le nombre de part des parents
  src/lib/hint.js
Labels: ⚡ fast review

#2825 Harmonise les events matomo en utilisant les id des aides plutot que le label
  src/components/benefit-cta.vue
Labels: development, bugfix

#2839 Ajoute le typescript
  .eslintrc.js
  cypress/plugins/index.js
  package-lock.json
  package.json
  src/components/support/copy-button.vue
  src/main.ts
  src/shims-vue.d.ts
  src/views/liste-aides.vue
  tools/mjml.js
  tsconfig.json
Labels: development

#2512 Effectue la migration des followups
  backend/controllers/followups.js
  backend/lib/email.js
  backend/lib/migrations/apply.js
  backend/lib/migrations/followups/create-followup-with-clean-id.js
  backend/lib/migrations/followups/delete-old-followups.js
  backend/lib/migrations/followups/to-v1.js
  backend/lib/migrations/followups/to-v2.js
  backend/lib/migrations/index.js
  backend/lib/migrations/looper.sh
  backend/lib/migrations/simulations/to-v1.js
  backend/lib/migrations/simulations/to-v2.js
  backend/lib/migrations/simulations/to-v3.js
  backend/lib/migrations/simulations/to-v4.js
  backend/lib/migrations/simulations/to-v5.js
  backend/lib/migrations/simulations/to-v6.js
  backend/lib/migrations/simulations/to-v7.js
  backend/lib/migrations/simulations/to-v8.js
  backend/lib/migrations/simulations/to-v9.js
  backend/models/followup.js
  tools/mjml.js
Labels: development

#2855 Modifie le wording des questions sur les types de ressources et corrige la question des ressources pour le conjoint et l'enfant
  lib/resources.js
  src/components/ressource/types.vue
Labels: ⚡ fast review

#2861 Corrige les liens de la page Statistiques
  src/views/stats.vue
Labels: ⚡ fast review

#2872 Corrige wording sur les ressources perçues
  lib/resources.js
Labels: ⚡ fast review

#2810 Génère les définitions à partir des fichiers de properties
  backend/lib/definitions.js
  backend/lib/openfisca/mapping/individu/index.js
  backend/lib/openfisca/mapping/last3-months-duplication.js
  lib/mutualized-steps.js
  lib/properties/famille-properties.js
  lib/properties/individu-properties.js
  lib/properties/menage-properties.js
  lib/properties/parents-properties.js
  lib/scolarite.js
  lib/utils.js
  src/components/ass-questions.vue
  src/lib/hint.js
  src/lib/mutualized-steps.js
  src/lib/recapitulatif.js
  src/mixins/droit-mixin.js
  src/views/simulation/enfants.vue
  src/views/simulation/mutualized-step.vue
  src/views/simulation/recapitulatif.vue
  src/views/simulation/resultats/attendu.vue
  tests/unit/definitions.spec.js
Labels: development

#2880 Simplifie l'utilisation des properties
  lib/answers.js
  lib/mutualized-steps.js
  lib/properties/famille-properties.js
  lib/properties/individu-properties.js
  lib/properties/menage-properties.js
  lib/properties/parents-properties.js
  src/composables/individu.ts
  src/views/simulation/mutualized-step.vue
  src/views/simulation/recapitulatif.vue
Labels: development

#2882 Ajoute `tns_autres_revenus_type_activite`
  backend/lib/definitions.js
Labels: development, bugfix
