Repository betagouv/aides-jeunes, pull requests merged in 2022-04, with the labels that each got.

#2670 Delete doublon aide pass monde etudes superieures
  data/benefits/javascript/normandie-pass-monde-etudes-superieures.yml
Labels: ⚡ fast review

#2596 Affiche les établissements d'une aide plutot que les établissements d'une institution
  data/benefits/openfisca/garantie_jeunes.yml
  data/institutions/garantie_jeunes.yml
  lib/benefits/etablissements.js
  src/components/benefit-cta.vue
  src/views/simulation/resultats/lieux.vue
Labels: development

#2648 Ajoute les questions pour la formation dans le sanitaire et social
  backend/lib/definitions.js
  contribuer/public/admin/config.yml
  cypress/integration/base.spec.js
  cypress/integration/family.spec.js
  cypress/integration/handicap.spec.js
  cypress/utils/profil.js
  cypress/utils/projet.js
  data/benefits/javascript/grand-est-bourse-du-secteur-sanitaire-et-social.yml
  data/benefits/javascript/hauts-de-france-aide-à-la-restauration-des-étudiants-boursiers-en-filière-sanitaire-et-sociale.yml
  lib/benefits/compute-javascript.js
  lib/situations.js
  lib/state/blocks.js
  src/lib/hint.js
  src/lib/individu-properties.js
Labels: development

#2515 [625] Ajout de l'accès au résultat de la simulation
  backend/controllers/followups.js
  backend/lib/mes-aides/emails/survey.js
  backend/models/followup.js
  src/views/accompagnement/liste.vue
Labels: development

#2674 fix: déplace le fichier bourse corse dans le bon répertoire
  data/benefits/javascript/departement-corse-bourse-animazioni.yml
Labels: ⚡ fast review

#2676 Répare le scroll hash et ajoute le scroll behavior smooth lors des redirections hash
  src/router.js
Labels: development, bugfix, ⚡ fast review

#2682 Corrige un bug du bot d'accompagnement
  backend/lib/mattermost-bot/poll-result.js
Labels: development, bugfix, ⚡ fast review

#2692 [652] Mettre à jour Netlify cms
  contribuer/public/admin/index.html
Labels: development, ⚡ fast review

#2691 Remplace les sélecteurs de classe par des sélecteurs sur le data-testid pour limiter la dépendance aux classes css
  cypress/utils/navigate.js
  cypress/utils/results.js
  src/components/droit-estime.vue
  src/components/droits-details.vue
  src/components/droits-list.vue
  src/views/aide.vue
  src/views/home.vue
  src/views/simulation/resultats-detail.vue
Labels: development, ⚡ fast review

#2686 Correctif/cleaning pour l'outil d'accompagnement
  backend/controllers/followups.js
  backend/routes/followups.js
  src/views/accompagnement/liste.vue
Labels: bugfix, ⚡ fast review

#2707 [695] Passe le paramètre célibataire en valeur permanente
  src/lib/parents-properties.js
  src/plugins/ab-testing-service.js
Labels: development, ⚡ fast review

#2708 Nettoie les pages de lieux et mutualise les boutons back
  lib/benefits/etablissements.js
  src/lib/etablissement.js
  src/modules/etablissement.js
  src/router.js
  src/views/lieux.vue
  src/views/lieux/details.vue
  src/views/simulation/resultats-detail.vue
  src/views/simulation/resultats/lieux-generiques.vue
  src/views/simulation/resultats/lieux.vue
Labels: development

#2694 [656] Lors de la création d'une institution, le code insee est optionnel dans l'interface mais obligatoire dans les tests
  contribuer/public/admin/config.yml
  contribuer/public/admin/main.js
Labels: development, bugfix, ⚡ fast review

#2727 [698] Retourne une erreur en cas de simulation non trouvée
  backend/controllers/simulation.js
Labels: development, bugfix, ⚡ fast review

#2733 [704] corrige les groupes fields après soumission d'un formulaire
  contribuer/public/admin/custom-controls.js
  contribuer/public/admin/main.js
Labels: development, bugfix, ⚡ fast review

#2738 Vérifie la présence d'un code Siren pour les institutions de type Epci
  tests/unit/benefits-description.spec.js
Labels: ⚡ fast review

#2744 [675] Mise à jour de Vue 3
  package-lock.json
  package.json
Labels: development

#2755 Créer un champ pour accéder à une simulation dans l'outil d'accompagnement
  backend/controllers/support.js
  backend/routes/support.js
  src/components/support/simulation-search.vue
  src/views/accompagnement/liste.vue
Labels: development

#2754 Amélioration de l'outil d'accompagnement
  src/views/accompagnement/liste.vue
Labels: development, ⚡ fast review

#2757 Amélioration du texte de l'outil d'accompagnement
  src/views/accompagnement/liste.vue
Labels: development, ⚡ fast review

#2764 Met à jour l'affichage des aides dans l'outil de contribution
  src/views/accompagnement/liste.vue
Labels: development, ⚡ fast review

#2745 Met à jour le package aides vélo
  data/institutions/ca_dagen.yml
  data/institutions/ca_du_bocage_bressuirais.yml
  data/institutions/ca_flers_agglo.yml
  data/institutions/cc_douarnenez_communaute.yml
  data/institutions/cc_du_haut_poitou.yml
  data/institutions/cc_terres_de_montaigu_cc_montaigu_rocheserviere.yml
  data/institutions/ville_bonningues_les_calais.yml
  data/institutions/ville_istres.yml
  data/institutions/ville_vauvert.yml
  data/institutions/ville_wasselonne.yml
  package-lock.json
  package.json
  public/img/logo_ca_dagen.png
  public/img/logo_ca_du_bocage_bressuirais.png
  public/img/logo_ca_flers_agglo.png
  public/img/logo_cc_douarnenez_communaute.png
  public/img/logo_cc_du_haut_poitou.png
  public/img/logo_cc_terres_de_montaigu_cc_montaigu_rocheserviere.png
  public/img/logo_ville_bonningues_les_calais.png
  public/img/logo_ville_istres.png
  public/img/logo_ville_vauvert.png
  public/img/logo_ville_wasselonne.png
Labels: ⚡ fast review

#2763 Ajoute un filtre Bénéficiaire du rsa
  contribuer/public/admin/config.yml
  data/benefits/javascript/benefit_front_test.yml
  data/benefits/javascript/grand-est-bourse-du-secteur-sanitaire-et-social.yml
  data/benefits/javascript/grand-est-mobilite-internationale-sanitaire-et-sociale.yml
  data/benefits/javascript/guadeloupe-bourse-sanitaire.yml
  data/benefits/javascript/guadeloupe-bourse-sociale.yml
  data/benefits/javascript/hauts-de-france-aide-restauration-etudiants-boursiers.yml
  data/benefits/javascript/hauts-de-france-aide-à-la-restauration-des-étudiants-boursiers-en-filière-sanitaire-et-sociale.yml
  data/benefits/javascript/hauts-de-france-bourses-etudes-sanitaires-et-sociales.yml
  data/benefits/javascript/hauts-de-france-fonds-regional-aide-urgence-sanitaire-social.yml
  data/benefits/javascript/hauts-de-france-formations-sanitaires-sociales-niveaux-3-4.yml
  data/benefits/javascript/hauts-de-france-mon-abo-etudiant-ter.yml
  data/benefits/javascript/ile-de-france-aide-au-merite.yml
  data/benefits/javascript/martinique-bourses-sanitaires-et-sociales.yml
  data/benefits/javascript/occitanie-bourse-etudes-sanitaires-et-sociales.yml
  data/benefits/javascript/provence-alpes-cote-azur-bourse-sanitaire-social.yml
  data/benefits/javascript/provence-alpes-cote-azur-fonds-sanitaire-social.yml
  data/benefits/javascript/region-bretagne-bourse-international-formation-sanitaires-sociales.yml
  data/benefits/javascript/region-bretagne-bourse-international-lycee-pro.yml
  data/benefits/javascript/region-ile-de-france-bourse-installtation-des-étudiants-en-kinésithérapie-et-maïeutique.yml
  data/benefits/javascript/region-occitanie-aide-au-merite-pour-les-etudiants-en-formations-sanitaires-et-sociales.yml
  data/benefits/javascript/region-provence-alpes-cote-azur-prame-sanitaire-et-social.yml
  data/benefits/javascript/region_auvergne_rhone_alpes-bourse-du-secteur-santé-social.yml
  data/benefits/javascript/region_bourgogne_franche_comte-bourses-détudes-sanitaires-et-sociales.yml
  data/benefits/javascript/region_bretagne-b-mouve-–-mobilité-des-formations-sanitaires-et-sociales.yml
  data/benefits/javascript/region_bretagne-qualif-sanitaire-et-social.yml
  data/benefits/javascript/region_centre_val_de_loire-aides-pour-la-formation-sanitaire-et-social.yml
  data/benefits/javascript/region_corse-bourses-d’études-de-formations-sanitaires-et-sociales.yml
  data/benefits/javascript/region_ile_de_france-bourses-pour-les-élèves-et-étudiant-e-s-inscrit-e-s-en-formations-sanitaires-et-sociales.yml
  data/benefits/javascript/region_la_reunion-bourse-régionale-sanitaire-et-sociale.yml
  data/benefits/javascript/region_normandie-aides-aux-formations-paramédicales-sociales-ou-de-santé.yml
  data/benefits/javascript/region_nouvelle_aquitaine-bourses-pour-les-étudiants-en-formations-sociales-paramédicales-et-de-santé.yml
  data/benefits/javascript/region_pays_de_la_loire-bourses-pour-les-élèves-et-étudiant-e-s-en-formation-sanitaire-et-sociale.yml
  lib/benefits/compute-javascript.js
Labels: development

#2777 Met à jour les openfisca
  openfisca/requirements.txt
Labels: development

#2571 Changement de l'age d'accès au pass culture
  data/benefits/openfisca/pass_culture.yml
Labels: development

#2553 [647] empêche le changement de valeur de champs number en cas de scroll
  src/components/input-number.vue
Labels: development, ⚡ fast review

#2778 Ajoute la propriété inputmode numeric
  src/components/input-date.vue
  src/components/input-depcom.vue
Labels: development, ⚡ fast review

#2780 Supprime puppeter
  backend/lib/utils.js
  configure.js
  docker-compose.yml
  docker/node/Dockerfile
  package-lock.json
  package.json
  tests/unit/pdf.js
Labels: development

#2789 Ajoute `collectivite-europeenne-alsace-fonds-aide-jeunes` dans les aides complexes pour le test sur les critères géographiques
  tests/unit/benefits-description.spec.js
Labels: development, bugfix, ⚡ fast review

#2796 Met à jour les packages vue cli en version stable
  package-lock.json
  package.json
Labels: development, ⚡ fast review

#2795 Supprime l'ancien système d'authentification sur l'outil de contribution
  backend/controllers/contributions.js
  backend/routes/contributions.js
Labels: development, ⚡ fast review

#2804 Fix/stats
  backend/config/index.js
  backend/lib/stats/mongodb.js
  docker-compose.yml
  pm2_config.yaml
Labels: development, bugfix, ⚡ fast review

#2783 [709] Migrer le projet sentry historique vers le sentry beta gouv
  configure.js
  src/main.js
Labels: development, ⚡ fast review

#2782 Ajoute un deuxième CTA pour envoyer des emails sur la page résultat
  src/components/buttons/send-recap-email-button.vue
  src/components/modal.vue
  src/components/modals/recap-email-modal.vue
  src/components/offline-results.vue
  src/components/titre-chapitre.vue
  src/store.js
  src/styles/partials/desktop/_ui-kit.scss
  src/styles/partials/mobile/_ui-kit.scss
  src/styles/partials/tablet/_ui-kit.scss
Labels: development

#2808 update: met à jour openfisca france
  openfisca/requirements.txt
Labels: development

#2793 Corrige le bug de simulation incomplète lors d'un retour arrière et dans le recap
  src/lib/recapitulatif.js
  src/views/simulation/resultats.vue
Labels: development

#2814 ajoute un profil d'éligibilité `beneficiaire_rsa`
  contribuer/public/admin/config.yml
  lib/benefits/compute-javascript.js
Labels: development, ⚡ fast review

#2779 Recharge l'ancienne simulation si dirty
  src/views/simulation/resultats.vue
Labels: development, bugfix, ⚡ fast review

#2803 Met à jour le README
  README.md
  package.json
Labels: ⚡ fast review
