Repository betagouv/aides-jeunes, pull requests merged in 2022-08, with the labels that each got.

#3121 Utilise une version de lodash adaptée à ESM
  backend/controllers/simulation.ts
  backend/lib/definitions.ts
  backend/lib/mes-aides/emails/initial.ts
  backend/lib/migrations/simulations/to-v11.js
  backend/lib/migrations/simulations/to-v2.js
  backend/lib/migrations/simulations/to-v3.js
  backend/lib/migrations/simulations/to-v8.js
  backend/lib/openfisca/mapping/common.ts
  backend/lib/openfisca/mapping/index.ts
  backend/lib/openfisca/mapping/individu/index.ts
  backend/lib/openfisca/mapping/individu/past-resources-proxy.ts
  backend/lib/openfisca/mapping/individu/ressources.ts
  backend/lib/openfisca/mapping/last3-months-duplication.ts
  backend/lib/openfisca/mapping/menage/index.ts
  backend/lib/openfisca/mapping/property-move.ts
  backend/lib/openfisca/test.ts
  backend/lib/stats/cli.ts
  backend/models/followup.ts
  lib/benefits/compute.ts
  lib/benefits/etablissements.ts
  lib/dates.ts
  lib/individu.ts
  lib/ressource.ts
  lib/types/individu.d.ts
  package-lock.json
  package.json
  src/components/input-date.vue
  src/components/ressource/types.vue
  src/lib/commune.js
  src/store.js
  src/stores/index.ts
  src/views/simulation/Ressources/fiscales.vue
  src/views/simulation/resultats/attendu.vue
Labels: development, ⚡ fast review

#3123 Simplifie l'attribut `label` de `ressourceCategories`
  lib/properties/others/complexe-properties.ts
  lib/resources.ts
  src/components/ressource/types.vue
  src/lib/recapitulatif.js
Labels: development, ⚡ fast review

#3122 Correction bug simulation sans depcom
  lib/benefits/compute.ts
Labels: development, bugfix, ⚡ fast review

#3131 Corrige le message de redirection qui s'affiche en permanence
  src/stores/index.ts
Labels: development, bugfix

#3061 Remplace id par `data-testid` pour simplifier l'utilisation des tests cypress lors de fork
  cypress/utils/form.js
  cypress/utils/foyer.js
  cypress/utils/logement.js
  cypress/utils/navigate.js
  cypress/utils/profil.js
  cypress/utils/results.js
  src/components/droits-details.vue
  src/components/input-date.vue
  src/components/input-depcom.vue
  src/components/input-number.vue
  src/components/multiple-answers.vue
  src/components/mutualized-step-title.vue
  src/views/home.vue
  src/views/simulation.vue
  src/views/simulation/Menage/loyer.vue
  src/views/simulation/enfants.vue
  src/views/simulation/mutualized-step.vue
Labels: development

#3128 Met à jour les tools et le système de migrations suite à la mise à jour ESM
  .github/workflows/check-links-validity.yaml
  .github/workflows/ci.yml
  README.md
  backend/controllers/simulation.ts
  backend/lib/migrations/apply.ts
  backend/lib/migrations/followups/create-followup-with-clean-id.js
  backend/lib/migrations/followups/delete-old-followups.js
  backend/lib/migrations/followups/to-v1.ts
  backend/lib/migrations/followups/to-v2.ts
  backend/lib/migrations/index.js
  backend/lib/migrations/index.ts
  backend/lib/migrations/simulations/to-v1.js
  backend/lib/migrations/simulations/to-v1.ts
  backend/lib/migrations/simulations/to-v10.ts
  backend/lib/migrations/simulations/to-v11.ts
  backend/lib/migrations/simulations/to-v12.ts
  backend/lib/migrations/simulations/to-v2.ts
  backend/lib/migrations/simulations/to-v3.ts
  backend/lib/migrations/simulations/to-v4.ts
  backend/lib/migrations/simulations/to-v5.ts
  backend/lib/migrations/simulations/to-v6.ts
  backend/lib/migrations/simulations/to-v7.ts
  backend/lib/migrations/simulations/to-v8.ts
  backend/lib/migrations/simulations/to-v9.ts
  package.json
  tools/check-links-validity.ts
  tools/cleaner.ts
  tools/evaluate-benefits.js
  tools/evaluate-benefits.ts
  tools/geographical-benefits-details.ts
  tools/get-all-steps.ts
  tools/mjml.ts
  tools/test-definition-periods.ts
Labels: development

#3137 Corrige le script CI check-links-validity
  .github/actions/reopen-issue-with-comment/main.js
Labels: development, bugfix

#3115 Footer affiché plus bas sur les pages
  src/styles/partials/desktop/_simulation.scss
  src/styles/partials/desktop/_ui-kit.scss
Labels: development

#3144 Fix lint commande
  package.json
Labels: development, bugfix, ⚡ fast review

#3146 Ajoute la question sur les enfants
  lib/properties/others/complexe-properties.ts
Labels: development, ⚡ fast review

#3141 Vérifie l'unicité des ids des institutions et des aides
  data/index.ts
  data/institutions/caf_gard.yml
  data/institutions/departements_et_metropoles.yml
  data/institutions/etat.yml
  tests/integration/test-benefit-ids.spec.js
  tests/integration/test-institution-ids.spec.js
Labels: development

#3166 Ajoute le workflow_dispatch
  .github/workflows/ci.yml
Labels: development

#3048 Mutualise le code du recapitulatif dans les steps
  backend/controllers/questions.ts
  lib/answers.ts
  lib/mutualized-steps.ts
  lib/properties/others/complexe-properties.ts
  lib/properties/others/simple-properties.ts
  lib/properties/property.ts
  lib/resources.ts
  lib/state/blocks.ts
  lib/state/index.ts
  lib/types/property.d.ts
  src/components/progress-bar.vue
  src/composables/progress.ts
  src/lib/recapitulatif.js
  src/mixins/progress-mixin.js
  src/views/simulation/recapitulatif.vue
Labels: development

#3133 Déplacer le calcul des résultats de simulation dans le back
  backend/controllers/simulation.ts
  backend/models/simulation.ts
  backend/routes/simulation.ts
  cypress/utils/navigate.js
  lib/benefits/compute.ts
  lib/types/store.d.ts
  mock.ts
  src/lib/institution.js
  src/mixins/resultats.js
  src/stores/index.ts
  src/views/simulation/resultats.vue
  src/views/simulation/resultats/attendu.vue
Labels: development

#3145 Ajoute dynamiquement les aides dans les templates d'emails
  lib/benefits/details.ts
  src/components/feedback.vue
  src/plugins/mails.js
Labels: development
