Repository betagouv/aides-jeunes, pull requests merged in 2022-06, with the labels that each got.

#2925 Ajoute un type d'aide à la liste de toutes les aides
  data/benefits/javascript/collectivite-europeenne-alsace-fonds-aide-jeunes.yml
  src/views/liste-aides.vue
Labels: ⚡ fast review

#2924 Diminue l'affichage de l'aide au permis pro btp
  cypress/utils/profil.js
  lib/benefits/compute-javascript.js
  lib/properties/individu-properties.js
  lib/scolarite.js
  lib/situations.js
  lib/state/blocks.js
  openfisca/requirements.txt
Labels: development

#2878 Refacto des properties en ajoutant le typage Typescript
  lib/mutualized-steps.js
  lib/mutualized-steps.ts
  lib/properties/famille-properties.ts
  lib/properties/individu-properties.ts
  lib/properties/menage-properties.ts
  lib/properties/parents-properties.ts
  lib/properties/property.ts
  lib/types/property.d.ts
  lib/utils.js
  src/views/simulation/mutualized-step.vue
  tsconfig.server.json
Labels: development

#2942 Ajoute le système de vérification des liens de aides-velo
  .github/actions/reopen-issue-with-comment/action.yaml
  .github/actions/reopen-issue-with-comment/main.js
  .github/workflows/check-links-validity.yaml
  package-lock.json
  package.json
  tools/check-links-validity.js
  tools/test-benefits-urls.js
Labels: development

#2948 Ajoute une ancre sur les titres d'institutions (Toutes les aides)
  src/views/liste-aides.vue
Labels: ⚡ fast review

#2954 Corrige handicap
  lib/properties/individu-properties.ts
Labels: bugfix

#2959 Supprime autoentrepreneur
  backend/lib/migrations/looper.sh
  backend/lib/migrations/simulations/to-v11.js
  cypress/integration/base.spec.js
  lib/resources.js
  lib/ressource.js
  package.json
  src/components/ressource/auto-entreprise.vue
  src/store.js
  src/views/simulation/Ressources/montants.vue
Labels: development

#2961 Met à jour l'aide `mobili_jeune`
  .github/workflows/ci.yml
  data/benefits/openfisca/mobili_jeune.yml
  openfisca/requirements.txt
  package.json
Labels: development

#2970 Envoie un message vers mattermost lorsque des liens morts sont détectés
  .github/workflows/check-links-validity.yaml
Labels: development, ⚡ fast review

#2968 Corrige la description des aides vélos avec des variables
  data/benefits/aides-velo-generator.js
  tests/unit/aides-velo-benefit-generator.spec.js
Labels: development

#2973 Met en capitalize le label des questions
  lib/properties/property.ts
Labels: development, bugfix

#2898 Refactorise le test qui valide le bon ajout de critères géographiques
  tests/integration/benefits-description.spec.js
  tests/integration/benefits-geographical-constraint-consistency.spec.js
  tools/test-benefits-geographical-constraint-consistency.js
Labels: development

#2997 Supprime le dossier dist-server avant de compiler
  package.json
Labels: development, ⚡ fast review
