Repository betagouv/aides-jeunes, pull requests merged in 2022-07, with the labels that each got.

#2985 Modifier bafa allier post maj caf.fr
  data/benefits/javascript/caf-allier-aide-bafa-session-generale.yml
Labels: todo

#2986 Maj bafa hautes alpes refonte caf.fr
  data/benefits/javascript/caf-hautes-alpes-aide-bafa-generale.yml
Labels: todo

#2999 Mutualise les propriétés de type Depcom
  backend/lib/definitions.js
  backend/lib/migrations/simulations/to-v12.js
  lib/properties/depcom-properties.ts
  lib/properties/property.ts
  lib/situations.js
  src/lib/recapitulatif.js
  src/mixins/depcom-mixin.js
  src/router.js
  src/views/simulation/depcom-step.vue
  src/views/simulation/individu/_bourse-criteres-sociaux-commune-domicile-familial.vue
Labels: development

#3022 Corrige la nouvelle version
  backend/lib/migrations/simulations/to-v12.js
  lib/simulation.js
Labels: development, bugfix, ⚡ fast review

#3015 Mutualise _first-name.vue
  backend/lib/definitions.js
  lib/properties/individu-properties.ts
  lib/properties/property.ts
  src/router.js
  src/views/simulation/individu/_first-name.vue
  src/views/simulation/mutualized-step.vue
Labels: development

#3029 Supprime le delete lors du build:server
  package.json
Labels: development, bugfix

#3033 Met à jour l'ordre d'affichage des résultats
  contribuer/public/admin/config.yml
  data/benefits/javascript/cohesion-territoires-conseillers-numeriques-france-services.yml
  data/benefits/javascript/pole-emploi-aif.yml
  data/benefits/openfisca/aide_logement.yml
  data/benefits/openfisca/apa_eligibilite.yml
  data/benefits/openfisca/crous_logement_eligibilite.yml
  data/benefits/openfisca/css_participation_forfaitaire.yml
  data/benefits/openfisca/depart1825_montant_maximum.yml
  data/benefits/openfisca/gratuite_musees_monuments.yml
  data/benefits/openfisca/livret_epargne_populaire_taux.yml
  data/benefits/openfisca/locapass_eligibilite.yml
  data/benefits/openfisca/logement_social_eligible.yml
  data/benefits/openfisca/ppa.yml
  data/benefits/openfisca/rsa.yml
  data/benefits/openfisca/seances_sante_psy_etudiant.yml
  data/benefits/openfisca/visale_eligibilite.yml
  data/index.js
  data/institutions/action_logement.yml
  data/institutions/etat.yml
  data/institutions/mutualite_sociale_agricole.yml
  data/institutions/pro_btp.yml
  data/institutions/sncf.yml
Labels: development

#2998 Implémente la redirection directe vers un téléservice pour l'affichage des résultats
  backend/controllers/teleservices/index.js
  backend/lib/teleservices/aides-jeunes-preremplissage.js
  backend/lib/teleservices/loiret.js
  backend/lib/teleservices/openfisca-axe.js
  backend/lib/teleservices/openfisca-response.js
  backend/lib/teleservices/openfisca-tracer.js
  backend/lib/teleservices/pnds.js
  backend/models/simulation.js
  src/views/simulation/resultats.vue
  tests/unit/teleservices/loiret.spec.js
Labels: development

#3045 Mise à jour image preview
  public/img/Twitter_1024x512.png
Labels: development, ⚡ fast review

#3017 Mutualise le titre de mutualized-step.vue
  .eslintrc.js
  src/components/mutualized-step-title.vue
  src/views/simulation/mutualized-step.vue
Labels: development

#2883 Ajoute la liste des questions (nom complexe)
  backend/controllers/questions.js
  backend/lib/openfisca/parameters.js
  backend/routes/questions.js
  lib/individu.js
  lib/logement.js
  lib/properties/famille-properties.ts
  lib/properties/individu-properties.ts
  lib/properties/menage-properties.ts
  lib/properties/others/complexe-properties.ts
  lib/properties/others/simple-properties.ts
  lib/properties/parents-properties.ts
  lib/properties/property.ts
  lib/state/blocks.js
  lib/types/property.d.ts
  package.json
  src/lib/recapitulatif.js
  src/views/simulation/Menage/loyer.vue
  src/views/simulation/logement.vue
Labels: development

#3018 Migre momentjs vers dayjs
  backend/controllers/teleservices/index.js
  backend/lib/openfisca/mapping/common.js
  backend/lib/openfisca/mapping/individu/index.js
  backend/lib/openfisca/mapping/individu/past-resources-proxy.js
  backend/lib/openfisca/mapping/menage/index.js
  backend/lib/openfisca/mapping/utils.js
  data/benefits/additional-attributes/index.js
  lib/benefits/compute-javascript.js
  lib/dates.js
  lib/individu.js
  lib/utils.js
  package-lock.json
  package.json
  src/components/ass-questions.vue
  src/components/input-date.vue
  src/components/month-input.vue
  src/lib/recapitulatif.js
  src/lib/situation.js
  src/main.ts
  src/store.js
  src/views/suivi.vue
  vue.config.js
Labels: development

#3058 Mise à jour du readme pour l'outil de contribution local
  README.md
Labels: development

#3089 Désactiver l'appel à l'API missingBenefits sur la production
  src/views/home.vue
Labels: development, bugfix

#3016 Ajoute un teleservice pour expérimenter l'évaluation des aides au logement paramétrique
  backend/controllers/teleservices/index.js
  backend/lib/teleservices/aides-jeunes-service-logement.js
  backend/routes/simulation.js
  package.json
Labels: development

#3093 Delete caf-pas-de-calais-aide-bafa-generale.yml
  data/benefits/javascript/caf-pas-de-calais-aide-bafa-generale.yml
Labels: todo

#3070 Suppression modeles
  contribuer/content/tasks/ajouter-une-aide-partie-1.md
  contribuer/content/tasks/ajouter-une-aide-partie-2.md
  contribuer/content/tasks/ajouter-une-institution.md
  contribuer/content/tasks/cibler-associations.md
  contribuer/content/tasks/cibler-elus.md
  contribuer/content/tasks/partager.md
  contribuer/content/tasks/utiliser.md
  contribuer/public/admin/config.yml
Labels: development

#3041 Ajoute un script mongo pour faciliter la réalisation d'exports
  .eslintrc.js
  tools/generate_mongo_stats.sh
  tools/mongo-query.js
Labels: development
