Repository betagouv/aides-jeunes, pull requests merged in 2023-08, with the labels that each got.

#3891 Crée Ville de Talence
  data/institutions/ville_talence.yml
  public/img/institutions/logo_ville_talence.png
Labels: ⚡ fast review

#3892 Crée Ville de Colomiers
  data/institutions/ville_colomiers.yml
  public/img/institutions/logo_ville_colomiers.png
Labels: ⚡ fast review

#3893 Crée Ville d'Anzin
  data/institutions/ville_anzin.yml
  public/img/institutions/logo_ville_anzin.png
Labels: ⚡ fast review

#3910 feat: envoyer une erreur 404 quand les coordonnées ne sont pas trouvées
  backend/controllers/outils.ts
  tests/unit/backend/outils.spec.ts
Labels: development

#3916 Met à jour les conditions non calculables de l'aide
  data/benefits/openfisca/aide_permis_pro_btp.yml
Labels: ⚡ fast review

#3900 Remplace le lien actuel du fsl du Val d'Oise vers une page plus explicite et utile pour les usagers
  data/benefits/dynamic/fsl.ts
Labels: ⚡ fast review

#3901 Corrige le lien plus d'info de l'aide bafa de la CNAF
  data/benefits/javascript/caf-aide-nationale-bafa.yml
Labels: ⚡ fast review

#3890 Crée la ville de Villeurbanne
  data/institutions/ville_villeurbanne.yml
  public/img/institutions/logo_ville_villeurbanne.png
Labels: ⚡ fast review

#3911 1421 bug affichage de undefined dans le recap de simulation
  lib/properties/others/complexe-properties.ts
Labels: development

#3919 feat: force no-cache for index page
  backend/server.ts
Labels: development

#3912 Ajoute le fichier yaml pour l'aide openfisca haute_vienne_aide_permis et l'institution haute-vienne
  data/benefits/openfisca/haute_vienne_aide_permis.yml
  data/institutions/departement_haute_vienne.yml
  public/img/institutions/logo_departement_haute_vienne.png
Labels: development

#3915 Transmet un RNI égale au RFR lorsque le demandeur est à la charge de ses parents
  backend/lib/openfisca/mapping/index.ts
Labels: development

#3917 Réparer la routine de vérification des liens dans Grist
  tools/check-links-validity.ts
Labels: development, ⚡ fast review

#3922 feat: Enleve l'ab-test sur le formulaire de followup
  backend/config/index.ts
  cypress/utils/results.js
  lib/enums/event-categories.ts
  src/components/buttons/send-recap-email-button.vue
  src/components/modals/recap-email-modal.vue
  src/plugins/ab-testing-service.ts
  src/router.ts
  src/views/simulation/resultats/recap-email.vue
Labels: development

#3925 Check des liens : fix sur la notification
  .github/workflows/check-links-validity.yaml
  backend/lib/mattermost-bot/mattermost.ts
  backend/lib/mattermost-bot/poll-result.ts
  tools/check-links-validity.ts
Labels: development

#3933 Renomme l'aide bafa de la caf Guyane
  data/benefits/javascript/caf-guyane-aide-bafa.yml
Labels: ⚡ fast review
