Repository betagouv/aides-jeunes, pull requests merged in 2023-04, with the labels that each got.

#3632 Mise à jour de l'aide aide dotation jeunes agriculteurs (Normandie)
  backend/lib/teleservices/demarches-simplifiees.ts
Labels: development

#3634 Correction de la structure du champ "commune" (préremplissage DS)
  backend/lib/teleservices/demarches-simplifiees.ts
Labels: development

#3631 Met à jour les dépendances Openfisca (france, local, paris)
  openfisca/requirements.txt
Labels: dependencies

#3587 Correction bug envoi statistiques
  src/components/benefit-cta.vue
  src/components/buttons/analytic-router-link.vue
  src/components/droit-estime.vue
Labels: development

#3636 Ajoute un lien d'accès au script d'intégration de l'iframe sur la page /iframe
  src/views/iframe.vue
Labels: development

#3596 Migration front js vers ts
  data/types/benefits.d.ts
  lib/types/benefits-categories.d.ts
  lib/types/commune.d.ts
  src/components/droits-details.vue
  src/components/en-savoir-plus-content.vue
  src/components/en-savoir-plus.vue
  src/components/input-depcom.vue
  src/components/resultat-inattendu/year-minus-two.vue
  src/lib/benefits-categories.ts
  src/lib/benefits.ts
  src/lib/commune.ts
  src/lib/contributions.js
  src/lib/contributions.ts
  src/lib/enums/nationality.ts
  src/lib/hint.ts
  src/lib/nationality.ts
  src/lib/simulation.js
  src/lib/simulation.ts
  src/lib/situation.ts
  src/lib/warnings.ts
  src/mixins/resultats.js
  src/router.js
  src/views/aide.vue
  src/views/simulation/depcom-step.vue
  src/views/simulation/enfants.vue
  src/views/simulation/mutualized-step.vue
  src/views/simulation/resultat-inattendu.vue
  src/views/simulation/resultats/attendu.vue
  src/views/suivi.vue
  tests/unit/src/lib/commune.spec.js
Labels: development

#3622 1214 service de stats
  lib/enums/behaviour-event-types.ts
  lib/types/benefits.d.ts
  lib/utils.ts
  src/components/benefit-cta-link.vue
  src/components/benefit-cta.vue
  src/components/buttons/analytic-router-link.vue
  src/components/droit-estime.vue
  src/components/droits-details.vue
  src/components/droits-list.vue
  src/components/en-savoir-plus.vue
  src/components/input-depcom.vue
  src/components/modals/recap-email-modal.vue
  src/directives/analytics.js
  src/directives/analytics.ts
  src/lib/statistics-service/matomo.ts
  src/lib/statistics-service/recorder.ts
  src/lib/statistics-service/shared.ts
  src/mixins/resultats.js
  src/mixins/statistics.js
  src/mixins/statistics.ts
  src/plugins/state-service.js
  src/views/simulation/resultats-detail.vue
  src/views/simulation/resultats.vue
  src/views/simulation/resultats/attendu.vue
  src/views/suivi.vue
  tests/unit/utils.spec.js
Labels: development

#3644 Corrige la redirection de l'outil accompagnement lors d'une connexion d'un utilisateur non autorisé
  backend/config/index.ts
  backend/controllers/github.ts
  src/views/accompagnement/accompagnement.vue
Labels: development

#3562 Refacto couleurs CSS & ajout thème Bordeaux métropole
  iframes/iframe-integration.js
  lib/enums/themes.ts
  lib/types/store.d.ts
  src/app.vue
  src/components/buttons/analytic-router-link.vue
  src/fonts/WorkSans-VariableFont_wght.ttf
  src/main.ts
  src/plugins/theme-service.ts
  src/router.js
  src/stores/index.ts
  src/styles/aides-jeunes.css
  src/styles/themes/bordeaux-metropole.css
  src/styles/themes/default-dsfr.css
  src/styles/themes/light-blue.css
  src/views/iframe.vue
Labels: development

#3654 Permet l'envoi de requêtes locales vers le stat-recorder en mode dev
  backend/config/development.ts
  src/lib/statistics-service/recorder.ts
Labels: development

#3659 Fix warnings eslint et ajoute une commande de formatage
  package.json
  src/components/droit-estime.vue
  src/components/droits-details.vue
Labels: development, ⚡ fast review

#3661 Fix and refacto le script d'anonymisation
  backend/models/simulation.ts
  lib/cleaner-functions.ts
  tests/unit/tools/cleaner.spec.js
  tools/cleaner.ts
Labels: development
