Repository betagouv/aides-jeunes, pull requests merged in 2023-09, with the labels that each got.

#3936 Vue Patrimoine: remove extra code
  src/views/simulation/Ressources/patrimoine.vue
Labels: development

#3938 Improve check links reliability
  .github/workflows/check-links-validity.yaml
  tools/check-links-validity.ts
Labels: development

#3945 Améliore la description de la carte d'abonnement SNCF pour les élèves, étudiants et apprentis
  data/benefits/openfisca/carte_sncf_eleve_apprenti_eligibilite.yml
Labels: ⚡ fast review

#3807 Ajoute un formulaire d'envoi de SMS (partie 2 - backend + frontend fusionnés)
  .github/workflows/ci.yml
  backend/config/continuous-integration.ts
  backend/config/development.ts
  backend/config/front-only.ts
  backend/config/index.ts
  backend/controllers/followups.ts
  backend/lib/followup-factory.ts
  backend/models/followup.ts
  backend/routes/sms.ts
  backend/types/config.d.ts
  cypress/e2e/base.cy.js
  cypress/utils/results.js
  lib/types/followup.d.ts
  lib/types/store.d.ts
  src/components/buttons/send-recap-button.vue
  src/components/buttons/send-recap-email-button.vue
  src/components/modals/errors-email-and-sms-modal.vue
  src/components/modals/recap-email-and-sms-modal.vue
  src/components/modals/recap-email-modal.vue
  src/components/offline-results.vue
  src/components/recap-email-and-sms-form.vue
  src/components/recap-email-form.vue
  src/components/titre-chapitre.vue
  src/stores/index.ts
  src/views/simulation/resultats.vue
  src/views/simulation/resultats/send-recap.vue
  tests/unit/backend/followup-factory.spec.ts
  tools/views/index.html
  vite.config.ts
Labels: development

#3957 Refacto contenu SMS
  backend/models/followup.ts
Labels: development

#3983 Convertit `crous_repas_un_euro_eligibilite` en `montant repas crous`
  data/benefits/openfisca/crous_repas_montant.yml
  data/benefits/openfisca/crous_repas_un_euro_eligibilite.yml
  openfisca/requirements.txt
Labels: development, ⚡ fast review

#3982 Corrige les liens d'aide dans les emails (pré-remplissage)
  backend/lib/mes-aides/emails/simulation-results.ts
Labels: development

#3964 Limite l'envoi de SMS aux numéros français
  backend/config/development.ts
  backend/config/index.ts
  backend/controllers/followups.ts
  backend/models/followup.ts
  backend/types/config.d.ts
  lib/phone-number.ts
  src/components/recap-email-and-sms-form.vue
  vite.config.ts
Labels: development

#4006 Ajoute preremplissage DS - Aide carte SNCF élève/apprenti
  backend/lib/teleservices/demarches-simplifiees.ts
  data/benefits/openfisca/carte_sncf_eleve_apprenti_eligibilite.yml
Labels: development

#3999 Ajoute l'aide pour les étudiants boursiers des Hauts-de-France : 100 repas du crous gratuits
  data/benefits/openfisca/crous_aide_100_repas_gratuits.yml
  openfisca/requirements.txt
Labels: development

#4011 Améliore l'écriture épicène de deux aides de la région Grand Est
  data/benefits/javascript/grand-est-bourse-du-secteur-sanitaire-et-social.yml
  data/benefits/javascript/grand-est-mobilite-internationale-sanitaire-et-sociale.yml
Labels: ⚡ fast review

#4010 Corrige des liens cassés sur deux aides régionales : Nouvelle Aquitaine et Centre Val de Loire
  data/benefits/javascript/region-centre-val-de-loire-le-combo-parfait-aide-a-la-formation.yml
  data/benefits/javascript/region_nouvelle_aquitaine-chèque-livre.yml
Labels: ⚡ fast review
