Repository betagouv/aides-jeunes, pull requests merged in 2023-02, with the labels that each got.

#3482 Corrige l'alignement des boutons oui/non du template email en mobile
  backend/lib/mes-aides/emails/templates/simulation-usefulness.mjml
Labels: development

#3490 Répare l'envoi de stats sur les CTA
  src/components/benefit-cta-link.vue
  src/directives/analytics.js
  src/mixins/statistics.js
  src/views/simulation/resultats-detail.vue
  src/views/simulation/resultats.vue
Labels: hotfix

#3492 Corrige le nom de l'évènement Matomo pour les clics sur montant inattendu
  src/components/droit-estime.vue
  src/router.js
Labels: hotfix

#3493 Corrige l'affichage de certaines aides
  lib/benefits/details.ts
Labels: hotfix

#3496 Ajout msa locale
  contribuer/public/admin/config.yml
  data/institutions/msa_armorique.yml
  data/institutions/msa_haute_normandie.yml
  data/institutions/msa_midi_pyrenees_sud.yml
  data/institutions/msa_nord_pas_de_calais.yml
  data/institutions/msa_portes_de_bretagne.yml
  rollup/institutions.ts
  src/views/liste-aides.vue
Labels: development

#3483 Corrige la variable baseURL utilisée dans les templates mjml
  backend/lib/mes-aides/emails/benefit-action.ts
  backend/lib/mes-aides/emails/simulation-usefulness.ts
Labels: development

#3499 Inverse l'ordre des éléments du sujet des emails
  src/components/resultat-inattendu/year-minus-two.vue
  src/mixins/feedback-utils.js
  src/plugins/mails.js
Labels: development

#3502 Met à jour les n° de version openfisca-france / local / paris
  openfisca/requirements.txt
Labels: dependencies

#3508 Fix la migration aidesvelo 3.0.8
  data/institutions/ca_saint_avold_synergie.yml
  data/institutions/cc_coeur_de_nacre.yml
  data/institutions/cc_du_bocage_mayennais.yml
  data/institutions/cc_loue_lison.yml
  data/institutions/cc_terre_demeraude_communaute.yml
  data/institutions/cu_limoges_metropole.yml
  data/institutions/ville_bourg_saint_maurice.yml
  data/institutions/ville_le_kremlin_bicetre.yml
  data/institutions/ville_lesquin.yml
  data/institutions/ville_noyarey.yml
  package-lock.json
  package.json
  public/img/institutions/logo_ca_saint_avold_synergie.png
  public/img/institutions/logo_cc_coeur_de_nacre.png
  public/img/institutions/logo_cc_du_bocage_mayennais.png
  public/img/institutions/logo_cc_loue_lison.png
  public/img/institutions/logo_cc_terre_demeraude_communaute.png
  public/img/institutions/logo_cu_limoges_metropole.png
  public/img/institutions/logo_ville_bourg_saint_maurice.png
  public/img/institutions/logo_ville_le_kremlin_bicetre.png
  public/img/institutions/logo_ville_lesquin.png
  public/img/institutions/logo_ville_noyarey.png
Labels: development

#3500 Ajoute un test e2e sur la page patrimoine (Cypress)
  .github/workflows/ci.yml
  cypress/e2e/patrimoine.cy.js
  cypress/utils/form.js
  cypress/utils/results.js
  lib/situations.ts
  src/components/yes-no-question.vue
  src/views/simulation/Ressources/patrimoine.vue
Labels: development

#3487 Migre les variables situationId vers simulationId
  backend/controllers/simulation.ts
  backend/lib/teleservices/openfisca-response.ts
  backend/models/simulation.ts
  lib/types/store.d.ts
  src/components/benefit-cta-link.vue
  src/components/error-block.vue
  src/components/feedback.vue
  src/components/support/copy-button.vue
  src/components/support/simulation-search.vue
  src/plugins/mails.js
  src/stores/index.ts
  src/views/confidentialite.vue
  src/views/redirection.vue
  src/views/simulation/resultats.vue
  src/views/simulation/resultats/attendu.vue
Labels: development

#3524 Mutualise les blocs dans les templates d'email
  backend/lib/mes-aides/emails/benefit-action.ts
  backend/lib/mes-aides/emails/email-render.ts
  backend/lib/mes-aides/emails/simulation-results.ts
  backend/lib/mes-aides/emails/simulation-usefulness.ts
  backend/lib/mes-aides/emails/templates/benefit-action.mjml
  backend/lib/mes-aides/emails/templates/email.mjml
  backend/lib/mes-aides/emails/templates/footer.mjml
  backend/lib/mes-aides/emails/templates/header.mjml
  backend/lib/mes-aides/emails/templates/simulation-results.mjml
  backend/lib/mes-aides/emails/templates/simulation-usefulness.mjml
  backend/models/followup.ts
  tools/mjml.ts
Labels: development

#3537 Corrige le texte d'email pour le LEP
  data/benefits/additional-attributes/index.ts
Labels: development

#3539 Reformulation question BAFA et BAFD
  lib/properties/individu-properties.ts
Labels: development

#3535 Changement ordre affichage sujet email
  backend/lib/mes-aides/emails/email-render.ts
  src/plugins/mails.js
  src/views/redirection.vue
Labels: development

#3545 Regroupe la logique de définition de constantes dans le script de configuration
  backend/configure.ts
  backend/dev.ts
  backend/server.ts
Labels: development
