Repository betagouv/aides-jeunes, pull requests merged in 2023-03, with the labels that each got.

#3552 [Outil de contribution ] Condition Boursier => onglet Scolarité
  contribuer/public/admin/config.yml
Labels: development

#3558 Améliore la réutilisabilité de l'ajout de logique aux aides
  data/index.ts
Labels: ⚡ fast review

#3559 Nettoyage du CSS
  src/components/bandeau-demo.vue
  src/components/buttons/send-recap-email-button.vue
  src/components/iframe-layout.vue
  src/components/progress.vue
  src/components/ressource/profession-liberale.vue
  src/components/resultat-inattendu/aide-logement.vue
  src/components/resultat-inattendu/contrat-engagement-jeune.vue
  src/components/resultat-inattendu/year-minus-two.vue
  src/components/summary.vue
  src/components/support/copy-button.vue
  src/components/titre-chapitre.vue
  src/components/yes-no-question.vue
  src/styles/aides-jeunes.css
  src/views/confidentialite.vue
  src/views/simulation.vue
  src/views/simulation/Menage/loyer.vue
  src/views/simulation/mutualized-step.vue
  src/views/simulation/resultats/attendu.vue
  src/views/suivi.vue
Labels: development

#3580 Met à jour le message d'info "en savoir plus" (question nombre part fiscale)
  lib/properties/parents-properties.ts
Labels: development, ⚡ fast review

#3582 Recueillir les statistiques d’affichage du lien “Montant Inattendu” dans la page résultat
  src/mixins/resultats.js
  src/views/simulation/resultats.vue
Labels: development

#3588 Supprime les reliquats de la page échelon boursier
  backend/lib/definitions.ts
  src/router.js
  src/views/simulation/individu/bourse-criteres-sociaux-echelon.vue
Labels: development

#3585 Met à joute le .gitignore pour les fichiers timestamp générés par Vite
  .gitignore
Labels: development

#3586 1191 ajouter des stats sur laffichage du lien pour prendre rdv
  src/views/suivi.vue
Labels: development
