Repository betagouv/aides-jeunes, pull requests merged in 2023-10, with the labels that each got.

#4021 1459 corriger les tags dans les emails pour quils soient effectivement enregistres dans tipimail
  backend/lib/smtp.ts
  backend/models/followup.ts
  lib/types/email.d.ts
Labels: development

#4017 fix: Ab test plus pertinent
  src/components/recap-email-and-sms-form.vue
Labels: bug

#4022 feat: Ajoute des statistiques sur les EPCI
  backend/lib/stats/funnel-service.ts
  backend/lib/stats/index.ts
  backend/lib/stats/institutions.ts
Labels: development

#4005 refactor: supprime la step vide de la page d'accueil dans blocks.ts
  lib/answers.ts
  lib/chapters.ts
  lib/enums/chapter.ts
  lib/state/blocks.ts
  lib/state/index.ts
  lib/types/chapters.d.ts
  lib/types/steps.d.ts
  src/components/action-buttons.vue
  src/stores/index.ts
  src/views/simulation.vue
Labels: development

#4027 feat: Permet de servir le dossier `/documents` en development
  backend/dev.ts
Labels: development

#4030 Supprime des classes css inexistantes
  lib/enums/behaviour-event.ts
  src/components/benefit-cta-link.vue
  src/components/droits-list.vue
  src/components/feedback.vue
  src/components/offline-results.vue
  src/components/support/copy-button.vue
  src/components/support/simulation-search.vue
  src/components/support/survey-email-search.vue
  src/views/liste-aides.vue
  src/views/simulation/Ressources/patrimoine.vue
  src/views/suivi.vue
Labels: development

#4036 Supprime des dependances
  package-lock.json
  package.json
Labels: development, ⚡ fast review

#4040 fix: Patch la liste des EPCI pour normaliser les metropôles.
  backend/lib/stats/institutions.ts
Labels: development, ⚡ fast review

#4013 feat: ajout enum EventAction & refactor
  lib/enums/behaviour-event.ts
  lib/enums/event-category.ts
  lib/enums/event.ts
  src/components/action-buttons.vue
  src/components/benefit-cta-link.vue
  src/components/benefit-cta.vue
  src/components/droit-estime.vue
  src/components/droits-details.vue
  src/components/en-savoir-plus.vue
  src/components/error-block.vue
  src/components/error-save-block.vue
  src/components/feedback.vue
  src/components/input-depcom.vue
  src/components/lieu-informations.vue
  src/components/lieu-light.vue
  src/components/recap-email-and-sms-form.vue
  src/directives/analytics.ts
  src/lib/statistics-service/matomo.ts
  src/lib/statistics-service/recorder.ts
  src/mixins/resultats.ts
  src/mixins/statistics.ts
  src/plugins/state-service.ts
  src/views/contact.vue
  src/views/home.vue
  src/views/redirection.vue
  src/views/simulation/resultats-detail.vue
  src/views/simulation/resultats.vue
  src/views/suivi.vue
Labels: development

#3801 Ajoute une route pour la récupération des RDV pris sur RDV-Aide-Numérique
  backend/config/index.ts
  backend/controllers/webhook.ts
  backend/routes-loader/api.ts
  backend/routes/webhook.ts
  backend/types/config.d.ts
  backend/types/rdv-aide-numerique.d.ts
  tests/unit/backend/webhook.spec.ts
Labels: development
