Repository betagouv/aides-jeunes, pull requests merged in 2023-07, with the labels that each got.

#3811 Fix erreur sentry - depcom required to loadLieux()
  src/composables/use-lieux.ts
Labels: development

#3842 Modifie les aides à la mobilité européenne de la Région CVL pour les apprentis et lycéens agricoles
  data/benefits/javascript/region-centre-val-de-loire-euro-metiers.yml
  data/benefits/javascript/region-centre-val-de-loire-mobilite-internationale-apprenti.yml
  data/benefits/javascript/region-centre-val-de-loire-mobilite-lyceen-agricole.yml
Labels: ⚡ fast review

#3823 Ajoute le champ conditions_benevoles dans les détails d'une aide
  backend/controllers/outils.ts
  backend/routes/outils.ts
  contribuer/public/admin/config.yml
  data/benefits/javascript/departement_charente_maritime-aide-departementale-au-permis-de-conduire.yml
  data/benefits/javascript/departement_cotes_d_armor-aide-departementale-au-permis-de-conduire-passengagement.yml
  data/benefits/javascript/departement_landes-aide-au-financement-du-permis-de-conduire-permis-citoyen.yml
  data/benefits/javascript/departement_oise-aide-au-financement-du-permis-de-conduire-permis-citoyen.yml
  data/benefits/javascript/departement_pas_de_calais-aide-au-financement-du-permis-de-conduire-permis-citoyen.yml
  data/benefits/javascript/mission-locale-de-lagglomeration-dhenin-carvin-aide-au-financement-du-permis-de-conduire-le-permis-cest-permis.yml
  data/benefits/javascript/region-bourgogne-franche-comte-jeunes-citoyens-du-monde.yml
  data/benefits/javascript/region-corse-aide-au-permis-prima-strada.yml
  data/benefits/javascript/ville-dangers-bourse-communale-pour-le-permis-de-conduire-permis-citoyen.yml
  data/benefits/javascript/ville-de-carcassonne-bourse-communale-au-permis-de-conduire.yml
  data/benefits/javascript/ville-de-lille-aide-au-financement-du-permis-de-conduire.yml
  data/benefits/javascript/ville-de-roubaix-bourse-communale-au-permis-de-conduire-passpermis.yml
  data/benefits/javascript/ville_chaumes_en_retz-bourse-communale-au-permis-de-conduire-et-au-bsr.yml
  data/benefits/javascript/ville_dunkerque-bourse-communale-au-permis-de-conduire.yml
  data/benefits/javascript/ville_nice-bourse-communale-au-permis-de-conduire-permis-citoyen.yml
  data/benefits/openfisca/iwuy_aide_mobilite_permis.yml
  data/benefits/openfisca/vendee_bourses_jeunes_benevoles_montant_max.yml
  src/components/droits-details.vue
  src/composables/use-voluntary-organisations.ts
Labels: development

#3857 Met à jour la description de la Bourse sur Critères Sociaux
  data/benefits/openfisca/bourse_criteres_sociaux.yml
Labels: ⚡ fast review

#3859 Supprime doublon de la bourse régionale d'études dans les secteurs du sanitaire et du travail social - Région PACA
  data/benefits/javascript/provence-alpes-cote-azur-bourse-sanitaire-social.yml
  data/benefits/javascript/provence-alpes-cote-azur-fonds-sanitaire-social.yml
Labels: ⚡ fast review

#3860 feat: Changement du texte du bouton
  src/views/suivi.vue
Labels: development, ⚡ fast review

#3850 Ajoute l'aide au permis de conduire de la gironde pour les jeunes ruraux
  data/benefits/javascript/departement-gironde-aide-departementale-au-permis-de-conduire.yml
Labels: ⚡ fast review

#3778 Ajoute un outil de suivi des liens dans Grist
  .github/actions/reopen-issue-with-comment/action.yaml
  .github/actions/reopen-issue-with-comment/main.js
  .github/actions/reopen-issue-with-comment/readme.md
  .github/has-file-changes.sh
  .github/workflows/check-links-validity.yaml
  .github/workflows/ci.yml
  lib/benefits/link-validity.ts
  lib/grist.ts
  lib/types/link-validity.d.ts
  package.json
  tests/unit/tools/link-validator/existing.spec.ts
  tests/unit/tools/link-validator/new.spec.ts
  tests/unit/tools/link-validator/utils.ts
  tools/check-links-validity.ts
Labels: development, Retours faits

#3863 Refacto stats scripts
  backend/config/index.ts
  backend/controllers/followups.ts
  backend/lib/migrations/apply.ts
  backend/lib/stats/cli.ts
  backend/lib/stats/index.ts
  backend/server.ts
Labels: development

#3867 Déplace le lien des résultats de simulation en haut du contenu du mail
  backend/lib/mes-aides/emails/templates/benefit-action.mjml
  backend/lib/mes-aides/emails/templates/footer.mjml
  backend/lib/mes-aides/emails/templates/simulation-results.mjml
  backend/lib/mes-aides/emails/templates/simulation-usefulness.mjml
Labels: development

#3870 Met à jour la description de l'aide au permis de conduire de la gironde
  data/benefits/javascript/departement_charente_maritime-aide-departementale-au-permis-de-conduire.yml
Labels: ⚡ fast review

#3871 Ajoute la condition bénévolat sur l'aide au permis de la gironde
  data/benefits/javascript/departement-gironde-aide-departementale-au-permis-de-conduire.yml
Labels: ⚡ fast review

#3874 Fix: matomo tracker (avec sentry)
  src/mixins/statistics.ts
Labels: development

#3879 Supprime la gestion d'erreur sentry sur le tracker matomo
  src/mixins/statistics.ts
Labels: development

#3875 Refactor la condition `taux incapacite` pour une gestion affinée
  contribuer/public/admin/config.yml
  data/benefits/javascript/intercommunalite_bordeaux-tarification-solidaire-des-transports.yml
  lib/benefits/compute-javascript.ts
  tests/unit/compute-javascript-benefits.spec.ts
Labels: development
