Repository betagouv/aides-jeunes, pull requests merged in 2023-05, with the labels that each got.

#3663 Met à jour les dépendances Openfisca (France, France-local et Paris) et intègre la notion d'orphelin.
  backend/lib/openfisca/mapping/individu/index.ts
  openfisca/requirements.txt
Labels: dependencies, development

#3649 Refacto Script Email - En amont de l'email tous à bord
  backend/enums/email.ts
  backend/lib/email.ts
  backend/lib/emails/sending.ts
Labels: development

#3670 Ajout de l'option `--max-warning 0` à l'étape de lint
  package.json
  src/views/simulation/resultats.vue
Labels: development

#3673 Ajoute une couleur au texte des boutons tertiary-no-outline
  src/styles/aides-jeunes.css
Labels: development

#3669 1278 par defaut la variable mongodburl devrait etre undefined
  backend/config/development.ts
  backend/config/index.ts
  backend/config/mongoose.ts
  backend/lib/stats/mongodb.ts
  backend/types/config.d.ts
Labels: development

#3718 Ajoute le logo de la ville de nice
  public/img/institutions/logo_ville_de_nice.png
Labels: ⚡ fast review

#3700 Sécurise le token d'accès github avec un jwt pour la page d'accompagnement
  backend/controllers/github.ts
  src/views/confidentialite.vue
Labels: development
